/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// TimerEventInfo struct for TimerEventInfo
type TimerEventInfo struct {
	Id *string `json:"Id,omitempty"`
	ProgramId *string `json:"ProgramId,omitempty"`
}
