/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// ItemCounts Class LibrarySummary.
type ItemCounts struct {
	// Gets or sets the movie count.
	MovieCount int32 `json:"MovieCount,omitempty"`
	// Gets or sets the series count.
	SeriesCount int32 `json:"SeriesCount,omitempty"`
	// Gets or sets the episode count.
	EpisodeCount int32 `json:"EpisodeCount,omitempty"`
	// Gets or sets the artist count.
	ArtistCount int32 `json:"ArtistCount,omitempty"`
	// Gets or sets the program count.
	ProgramCount int32 `json:"ProgramCount,omitempty"`
	// Gets or sets the trailer count.
	TrailerCount int32 `json:"TrailerCount,omitempty"`
	// Gets or sets the song count.
	SongCount int32 `json:"SongCount,omitempty"`
	// Gets or sets the album count.
	AlbumCount int32 `json:"AlbumCount,omitempty"`
	// Gets or sets the music video count.
	MusicVideoCount int32 `json:"MusicVideoCount,omitempty"`
	// Gets or sets the box set count.
	BoxSetCount int32 `json:"BoxSetCount,omitempty"`
	// Gets or sets the book count.
	BookCount int32 `json:"BookCount,omitempty"`
	// Gets or sets the item count.
	ItemCount int32 `json:"ItemCount,omitempty"`
}
