/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// IScheduledTaskWorker Interface IScheduledTaskWorker.
type IScheduledTaskWorker struct {
	ScheduledTask IScheduledTask `json:"ScheduledTask,omitempty"`
	LastExecutionResult TaskResult `json:"LastExecutionResult,omitempty"`
	// Gets the name.
	Name *string `json:"Name,omitempty"`
	// Gets the description.
	Description *string `json:"Description,omitempty"`
	// Gets the category.
	Category *string `json:"Category,omitempty"`
	State TaskState `json:"State,omitempty"`
	// Gets the current progress.
	CurrentProgress *float64 `json:"CurrentProgress,omitempty"`
	// Gets the triggers that define when the task will run.
	Triggers *[]TaskTriggerInfo `json:"Triggers,omitempty"`
	// Gets the unique id.
	Id *string `json:"Id,omitempty"`
}
