/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// TransportStreamTimestamp the model 'TransportStreamTimestamp'
type TransportStreamTimestamp string

// List of TransportStreamTimestamp
const (
	TRANSPORTSTREAMTIMESTAMP_NONE TransportStreamTimestamp = "None"
	TRANSPORTSTREAMTIMESTAMP_ZERO TransportStreamTimestamp = "Zero"
	TRANSPORTSTREAMTIMESTAMP_VALID TransportStreamTimestamp = "Valid"
)
