/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// ObjectGroupUpdate Class GroupUpdate.
type ObjectGroupUpdate struct {
	// Gets or sets the group identifier.
	GroupId *string `json:"GroupId,omitempty"`
	Type GroupUpdateType `json:"Type,omitempty"`
	// Gets or sets the data.
	Data *interface{} `json:"Data,omitempty"`
}
