/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// TaskInfo Class TaskInfo.
type TaskInfo struct {
	// Gets or sets the name.
	Name *string `json:"Name,omitempty"`
	State TaskState `json:"State,omitempty"`
	// Gets or sets the progress.
	CurrentProgressPercentage *float64 `json:"CurrentProgressPercentage,omitempty"`
	// Gets or sets the id.
	Id *string `json:"Id,omitempty"`
	LastExecutionResult TaskResult `json:"LastExecutionResult,omitempty"`
	// Gets or sets the triggers.
	Triggers *[]TaskTriggerInfo `json:"Triggers,omitempty"`
	// Gets or sets the description.
	Description *string `json:"Description,omitempty"`
	// Gets or sets the category.
	Category *string `json:"Category,omitempty"`
	// Gets or sets a value indicating whether this instance is hidden.
	IsHidden bool `json:"IsHidden,omitempty"`
	// Gets or sets the key.
	Key *string `json:"Key,omitempty"`
}
