/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// Video3DFormat the model 'Video3DFormat'
type Video3DFormat string

// List of Video3DFormat
const (
	VIDEO3DFORMAT_HALF_SIDE_BY_SIDE Video3DFormat = "HalfSideBySide"
	VIDEO3DFORMAT_FULL_SIDE_BY_SIDE Video3DFormat = "FullSideBySide"
	VIDEO3DFORMAT_FULL_TOP_AND_BOTTOM Video3DFormat = "FullTopAndBottom"
	VIDEO3DFORMAT_HALF_TOP_AND_BOTTOM Video3DFormat = "HalfTopAndBottom"
	VIDEO3DFORMAT_MVC Video3DFormat = "MVC"
)
