/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// QueueItem struct for QueueItem
type QueueItem struct {
	Id string `json:"Id,omitempty"`
	PlaylistItemId *string `json:"PlaylistItemId,omitempty"`
}
