/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// RatingType the model 'RatingType'
type RatingType string

// List of RatingType
const (
	RATINGTYPE_SCORE RatingType = "Score"
	RATINGTYPE_LIKES RatingType = "Likes"
)
