/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// DeviceProfileDto Device profile dto.
type DeviceProfileDto struct {
	DeviceProfile DeviceProfile `json:"DeviceProfile,omitempty"`
}
