/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// MetadataRefreshMode the model 'MetadataRefreshMode'
type MetadataRefreshMode string

// List of MetadataRefreshMode
const (
	METADATAREFRESHMODE_NONE MetadataRefreshMode = "None"
	METADATAREFRESHMODE_VALIDATION_ONLY MetadataRefreshMode = "ValidationOnly"
	METADATAREFRESHMODE_DEFAULT MetadataRefreshMode = "Default"
	METADATAREFRESHMODE_FULL_REFRESH MetadataRefreshMode = "FullRefresh"
)
