/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// ChannelType Enum ChannelType.
type ChannelType string

// List of ChannelType
const (
	CHANNELTYPE_TV ChannelType = "TV"
	CHANNELTYPE_RADIO ChannelType = "Radio"
)
