/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// PlayMethod the model 'PlayMethod'
type PlayMethod string

// List of PlayMethod
const (
	PLAYMETHOD_TRANSCODE PlayMethod = "Transcode"
	PLAYMETHOD_DIRECT_STREAM PlayMethod = "DirectStream"
	PLAYMETHOD_DIRECT_PLAY PlayMethod = "DirectPlay"
)
