/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// BaseItemDtoImageTags Gets or sets the image tags.
type BaseItemDtoImageTags struct {
	Primary string `json:"Primary,omitempty"`
	Art string `json:"Art,omitempty"`
	Backdrop string `json:"Backdrop,omitempty"`
	Banner string `json:"Banner,omitempty"`
	Logo string `json:"Logo,omitempty"`
	Thumb string `json:"Thumb,omitempty"`
	Disc string `json:"Disc,omitempty"`
	Box string `json:"Box,omitempty"`
	Screenshot string `json:"Screenshot,omitempty"`
	Menu string `json:"Menu,omitempty"`
	Chapter string `json:"Chapter,omitempty"`
	BoxRear string `json:"BoxRear,omitempty"`
	Profile string `json:"Profile,omitempty"`
}
