/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// ContainerProfile struct for ContainerProfile
type ContainerProfile struct {
	Type DlnaProfileType `json:"Type,omitempty"`
	Conditions *[]ProfileCondition `json:"Conditions,omitempty"`
	Container *string `json:"Container,omitempty"`
}
