/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// MediaUpdateInfoDto Media Update Info Dto.
type MediaUpdateInfoDto struct {
	// Gets or sets media path.
	Path *string `json:"Path,omitempty"`
	// Gets or sets media update type.  Created, Modified, Deleted.
	UpdateType *string `json:"UpdateType,omitempty"`
}
