/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// WakeOnLanInfo Provides the MAC address and port for wake-on-LAN functionality.
type WakeOnLanInfo struct {
	// Gets the MAC address of the device.
	MacAddress *string `json:"MacAddress,omitempty"`
	// Gets or sets the wake-on-LAN port.
	Port int32 `json:"Port,omitempty"`
}
