/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// PlaystateRequest struct for PlaystateRequest
type PlaystateRequest struct {
	Command PlaystateCommand `json:"Command,omitempty"`
	SeekPositionTicks *int64 `json:"SeekPositionTicks,omitempty"`
	// Gets or sets the controlling user identifier.
	ControllingUserId *string `json:"ControllingUserId,omitempty"`
}
