/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// ChannelMediaType the model 'ChannelMediaType'
type ChannelMediaType string

// List of ChannelMediaType
const (
	CHANNELMEDIATYPE_AUDIO ChannelMediaType = "Audio"
	CHANNELMEDIATYPE_VIDEO ChannelMediaType = "Video"
	CHANNELMEDIATYPE_PHOTO ChannelMediaType = "Photo"
)
