/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// ChannelMappingOptionsDto Channel mapping options dto.
type ChannelMappingOptionsDto struct {
	// Gets or sets list of tuner channels.
	TunerChannels *[]TunerChannelMapping `json:"TunerChannels,omitempty"`
	// Gets or sets list of provider channels.
	ProviderChannels *[]NameIdPair `json:"ProviderChannels,omitempty"`
	// Gets or sets list of mappings.
	Mappings *[]NameValuePair `json:"Mappings,omitempty"`
	// Gets or sets provider name.
	ProviderName *string `json:"ProviderName,omitempty"`
}
