/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// RepeatMode the model 'RepeatMode'
type RepeatMode string

// List of RepeatMode
const (
	REPEATMODE_REPEAT_NONE RepeatMode = "RepeatNone"
	REPEATMODE_REPEAT_ALL RepeatMode = "RepeatAll"
	REPEATMODE_REPEAT_ONE RepeatMode = "RepeatOne"
)
