/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// MediaStreamType Enum MediaStreamType.
type MediaStreamType string

// List of MediaStreamType
const (
	MEDIASTREAMTYPE_AUDIO MediaStreamType = "Audio"
	MEDIASTREAMTYPE_VIDEO MediaStreamType = "Video"
	MEDIASTREAMTYPE_SUBTITLE MediaStreamType = "Subtitle"
	MEDIASTREAMTYPE_EMBEDDED_IMAGE MediaStreamType = "EmbeddedImage"
)
