/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// MediaSourceInfo struct for MediaSourceInfo
type MediaSourceInfo struct {
	Protocol MediaProtocol `json:"Protocol,omitempty"`
	Id *string `json:"Id,omitempty"`
	Path *string `json:"Path,omitempty"`
	EncoderPath *string `json:"EncoderPath,omitempty"`
	EncoderProtocol MediaProtocol `json:"EncoderProtocol,omitempty"`
	Type MediaSourceType `json:"Type,omitempty"`
	Container *string `json:"Container,omitempty"`
	Size *int64 `json:"Size,omitempty"`
	Name *string `json:"Name,omitempty"`
	// Differentiate internet url vs local network.
	IsRemote bool `json:"IsRemote,omitempty"`
	ETag *string `json:"ETag,omitempty"`
	RunTimeTicks *int64 `json:"RunTimeTicks,omitempty"`
	ReadAtNativeFramerate bool `json:"ReadAtNativeFramerate,omitempty"`
	IgnoreDts bool `json:"IgnoreDts,omitempty"`
	IgnoreIndex bool `json:"IgnoreIndex,omitempty"`
	GenPtsInput bool `json:"GenPtsInput,omitempty"`
	SupportsTranscoding bool `json:"SupportsTranscoding,omitempty"`
	SupportsDirectStream bool `json:"SupportsDirectStream,omitempty"`
	SupportsDirectPlay bool `json:"SupportsDirectPlay,omitempty"`
	IsInfiniteStream bool `json:"IsInfiniteStream,omitempty"`
	RequiresOpening bool `json:"RequiresOpening,omitempty"`
	OpenToken *string `json:"OpenToken,omitempty"`
	RequiresClosing bool `json:"RequiresClosing,omitempty"`
	LiveStreamId *string `json:"LiveStreamId,omitempty"`
	BufferMs *int32 `json:"BufferMs,omitempty"`
	RequiresLooping bool `json:"RequiresLooping,omitempty"`
	SupportsProbing bool `json:"SupportsProbing,omitempty"`
	VideoType VideoType `json:"VideoType,omitempty"`
	IsoType IsoType `json:"IsoType,omitempty"`
	Video3DFormat Video3DFormat `json:"Video3DFormat,omitempty"`
	MediaStreams *[]MediaStream `json:"MediaStreams,omitempty"`
	MediaAttachments *[]MediaAttachment `json:"MediaAttachments,omitempty"`
	Formats *[]string `json:"Formats,omitempty"`
	Bitrate *int32 `json:"Bitrate,omitempty"`
	Timestamp TransportStreamTimestamp `json:"Timestamp,omitempty"`
	RequiredHttpHeaders *map[string]string `json:"RequiredHttpHeaders,omitempty"`
	TranscodingUrl *string `json:"TranscodingUrl,omitempty"`
	TranscodingSubProtocol *string `json:"TranscodingSubProtocol,omitempty"`
	TranscodingContainer *string `json:"TranscodingContainer,omitempty"`
	AnalyzeDurationMs *int32 `json:"AnalyzeDurationMs,omitempty"`
	DefaultAudioStreamIndex *int32 `json:"DefaultAudioStreamIndex,omitempty"`
	DefaultSubtitleStreamIndex *int32 `json:"DefaultSubtitleStreamIndex,omitempty"`
}
