/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
import (
	"time"
)
// AuthenticationInfo struct for AuthenticationInfo
type AuthenticationInfo struct {
	// Gets or sets the identifier.
	Id int64 `json:"Id,omitempty"`
	// Gets or sets the access token.
	AccessToken *string `json:"AccessToken,omitempty"`
	// Gets or sets the device identifier.
	DeviceId *string `json:"DeviceId,omitempty"`
	// Gets or sets the name of the application.
	AppName *string `json:"AppName,omitempty"`
	// Gets or sets the application version.
	AppVersion *string `json:"AppVersion,omitempty"`
	// Gets or sets the name of the device.
	DeviceName *string `json:"DeviceName,omitempty"`
	// Gets or sets the user identifier.
	UserId string `json:"UserId,omitempty"`
	// Gets or sets a value indicating whether this instance is active.
	IsActive bool `json:"IsActive,omitempty"`
	// Gets or sets the date created.
	DateCreated time.Time `json:"DateCreated,omitempty"`
	// Gets or sets the date revoked.
	DateRevoked *time.Time `json:"DateRevoked,omitempty"`
	DateLastActivity time.Time `json:"DateLastActivity,omitempty"`
	UserName *string `json:"UserName,omitempty"`
}
