/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// SubtitleDeliveryMethod the model 'SubtitleDeliveryMethod'
type SubtitleDeliveryMethod string

// List of SubtitleDeliveryMethod
const (
	SUBTITLEDELIVERYMETHOD_ENCODE SubtitleDeliveryMethod = "Encode"
	SUBTITLEDELIVERYMETHOD_EMBED SubtitleDeliveryMethod = "Embed"
	SUBTITLEDELIVERYMETHOD_EXTERNAL SubtitleDeliveryMethod = "External"
	SUBTITLEDELIVERYMETHOD_HLS SubtitleDeliveryMethod = "Hls"
)
