/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// CountryInfo Class CountryInfo.
type CountryInfo struct {
	// Gets or sets the name.
	Name *string `json:"Name,omitempty"`
	// Gets or sets the display name.
	DisplayName *string `json:"DisplayName,omitempty"`
	// Gets or sets the name of the two letter ISO region.
	TwoLetterISORegionName *string `json:"TwoLetterISORegionName,omitempty"`
	// Gets or sets the name of the three letter ISO region.
	ThreeLetterISORegionName *string `json:"ThreeLetterISORegionName,omitempty"`
}
