/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// VersionInfo Class PackageVersionInfo.
type VersionInfo struct {
	// Gets or sets the version.
	Version *string `json:"version,omitempty"`
	// Gets or sets the changelog for this version.
	Changelog *string `json:"changelog,omitempty"`
	// Gets or sets the ABI that this version was built against.
	TargetAbi *string `json:"targetAbi,omitempty"`
	// Gets or sets the source URL.
	SourceUrl *string `json:"sourceUrl,omitempty"`
	// Gets or sets a checksum for the binary.
	Checksum *string `json:"checksum,omitempty"`
	// Gets or sets a timestamp of when the binary was built.
	Timestamp *string `json:"timestamp,omitempty"`
}
