/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
import (
	"time"
)
// ActivityLogEntry struct for ActivityLogEntry
type ActivityLogEntry struct {
	// Gets or sets the identifier.
	Id int64 `json:"Id,omitempty"`
	// Gets or sets the name.
	Name *string `json:"Name,omitempty"`
	// Gets or sets the overview.
	Overview *string `json:"Overview,omitempty"`
	// Gets or sets the short overview.
	ShortOverview *string `json:"ShortOverview,omitempty"`
	// Gets or sets the type.
	Type *string `json:"Type,omitempty"`
	// Gets or sets the item identifier.
	ItemId *string `json:"ItemId,omitempty"`
	// Gets or sets the date.
	Date time.Time `json:"Date,omitempty"`
	// Gets or sets the user identifier.
	UserId string `json:"UserId,omitempty"`
	// Gets or sets the user primary image tag.
	UserPrimaryImageTag *string `json:"UserPrimaryImageTag,omitempty"`
	Severity LogLevel `json:"Severity,omitempty"`
}
