/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// SpecialViewOptionDto Special view option dto.
type SpecialViewOptionDto struct {
	// Gets or sets view option name.
	Name *string `json:"Name,omitempty"`
	// Gets or sets view option id.
	Id *string `json:"Id,omitempty"`
}
