/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// SortOrder An enum representing the sorting order.
type SortOrder string

// List of SortOrder
const (
	SORTORDER_ASCENDING SortOrder = "Ascending"
	SORTORDER_DESCENDING SortOrder = "Descending"
)
