/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// AuthenticateUserByName The authenticate user by name request body.
type AuthenticateUserByName struct {
	// Gets or sets the username.
	Username *string `json:"Username,omitempty"`
	// Gets or sets the plain text password.
	Pw *string `json:"Pw,omitempty"`
	// Gets or sets the sha1-hashed password.
	Password *string `json:"Password,omitempty"`
}
