/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// IsoType Enum IsoType.
type IsoType string

// List of IsoType
const (
	ISOTYPE_DVD IsoType = "Dvd"
	ISOTYPE_BLU_RAY IsoType = "BluRay"
)
