/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// ExternalUrl struct for ExternalUrl
type ExternalUrl struct {
	// Gets or sets the name.
	Name *string `json:"Name,omitempty"`
	// Gets or sets the type of the item.
	Url *string `json:"Url,omitempty"`
}
