/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// BaseItemPersonImageBlurHashesPrimary struct for BaseItemPersonImageBlurHashesPrimary
type BaseItemPersonImageBlurHashesPrimary struct {
	String string `json:"string,omitempty"`
}
