/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// LibraryUpdateInfo Class LibraryUpdateInfo.
type LibraryUpdateInfo struct {
	// Gets or sets the folders added to.
	FoldersAddedTo *[]string `json:"FoldersAddedTo,omitempty"`
	// Gets or sets the folders removed from.
	FoldersRemovedFrom *[]string `json:"FoldersRemovedFrom,omitempty"`
	// Gets or sets the items added.
	ItemsAdded *[]string `json:"ItemsAdded,omitempty"`
	// Gets or sets the items removed.
	ItemsRemoved *[]string `json:"ItemsRemoved,omitempty"`
	// Gets or sets the items updated.
	ItemsUpdated *[]string `json:"ItemsUpdated,omitempty"`
	CollectionFolders *[]string `json:"CollectionFolders,omitempty"`
	IsEmpty bool `json:"IsEmpty,omitempty"`
}
