/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// NotificationsSummaryDto The notification summary DTO.
type NotificationsSummaryDto struct {
	// Gets or sets the number of unread notifications.
	UnreadCount int32 `json:"UnreadCount,omitempty"`
	MaxUnreadNotificationLevel NotificationLevel `json:"MaxUnreadNotificationLevel,omitempty"`
}
