/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// BaseItemPersonImageBlurHashes Gets or sets the primary image blurhash.
type BaseItemPersonImageBlurHashes struct {
	Primary BaseItemPersonImageBlurHashesPrimary `json:"Primary,omitempty"`
	Art BaseItemPersonImageBlurHashesPrimary `json:"Art,omitempty"`
	Backdrop BaseItemPersonImageBlurHashesPrimary `json:"Backdrop,omitempty"`
	Banner BaseItemPersonImageBlurHashesPrimary `json:"Banner,omitempty"`
	Logo BaseItemPersonImageBlurHashesPrimary `json:"Logo,omitempty"`
	Thumb BaseItemPersonImageBlurHashesPrimary `json:"Thumb,omitempty"`
	Disc BaseItemPersonImageBlurHashesPrimary `json:"Disc,omitempty"`
	Box BaseItemPersonImageBlurHashesPrimary `json:"Box,omitempty"`
	Screenshot BaseItemPersonImageBlurHashesPrimary `json:"Screenshot,omitempty"`
	Menu BaseItemPersonImageBlurHashesPrimary `json:"Menu,omitempty"`
	Chapter BaseItemPersonImageBlurHashesPrimary `json:"Chapter,omitempty"`
	BoxRear BaseItemPersonImageBlurHashesPrimary `json:"BoxRear,omitempty"`
	Profile BaseItemPersonImageBlurHashesPrimary `json:"Profile,omitempty"`
}
