/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// Architecture the model 'Architecture'
type Architecture string

// List of Architecture
const (
	ARCHITECTURE_X86 Architecture = "X86"
	ARCHITECTURE_X64 Architecture = "X64"
	ARCHITECTURE_ARM Architecture = "Arm"
	ARCHITECTURE_ARM64 Architecture = "Arm64"
)
