/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// CodecProfile struct for CodecProfile
type CodecProfile struct {
	Type CodecType `json:"Type,omitempty"`
	Conditions *[]ProfileCondition `json:"Conditions,omitempty"`
	ApplyConditions *[]ProfileCondition `json:"ApplyConditions,omitempty"`
	Codec *string `json:"Codec,omitempty"`
	Container *string `json:"Container,omitempty"`
}
