/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
import (
	"time"
)
// BaseItem Class BaseItem.
type BaseItem struct {
	Size *int64 `json:"Size,omitempty"`
	Container *string `json:"Container,omitempty"`
	DateLastSaved time.Time `json:"DateLastSaved,omitempty"`
	// Gets or sets the remote trailers.
	RemoteTrailers *[]MediaUrl `json:"RemoteTrailers,omitempty"`
	IsHD bool `json:"IsHD,omitempty"`
	IsShortcut bool `json:"IsShortcut,omitempty"`
	ShortcutPath *string `json:"ShortcutPath,omitempty"`
	Width int32 `json:"Width,omitempty"`
	Height int32 `json:"Height,omitempty"`
	ExtraIds *[]string `json:"ExtraIds,omitempty"`
	SupportsExternalTransfer bool `json:"SupportsExternalTransfer,omitempty"`
}
