/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// DirectPlayProfile struct for DirectPlayProfile
type DirectPlayProfile struct {
	Container *string `json:"Container,omitempty"`
	AudioCodec *string `json:"AudioCodec,omitempty"`
	VideoCodec *string `json:"VideoCodec,omitempty"`
	Type DlnaProfileType `json:"Type,omitempty"`
}
