/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// ChannelMediaContentType the model 'ChannelMediaContentType'
type ChannelMediaContentType string

// List of ChannelMediaContentType
const (
	CHANNELMEDIACONTENTTYPE_CLIP ChannelMediaContentType = "Clip"
	CHANNELMEDIACONTENTTYPE_PODCAST ChannelMediaContentType = "Podcast"
	CHANNELMEDIACONTENTTYPE_TRAILER ChannelMediaContentType = "Trailer"
	CHANNELMEDIACONTENTTYPE_MOVIE ChannelMediaContentType = "Movie"
	CHANNELMEDIACONTENTTYPE_EPISODE ChannelMediaContentType = "Episode"
	CHANNELMEDIACONTENTTYPE_SONG ChannelMediaContentType = "Song"
	CHANNELMEDIACONTENTTYPE_MOVIE_EXTRA ChannelMediaContentType = "MovieExtra"
	CHANNELMEDIACONTENTTYPE_TV_EXTRA ChannelMediaContentType = "TvExtra"
)
