/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// BaseItemPerson This is used by the api to get information about a Person within a BaseItem.
type BaseItemPerson struct {
	// Gets or sets the name.
	Name *string `json:"Name,omitempty"`
	// Gets or sets the identifier.
	Id *string `json:"Id,omitempty"`
	// Gets or sets the role.
	Role *string `json:"Role,omitempty"`
	// Gets or sets the type.
	Type *string `json:"Type,omitempty"`
	// Gets or sets the primary image tag.
	PrimaryImageTag *string `json:"PrimaryImageTag,omitempty"`
	ImageBlurHashes *BaseItemPersonImageBlurHashes `json:"ImageBlurHashes,omitempty"`
}
