/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// QueryFilters struct for QueryFilters
type QueryFilters struct {
	Genres *[]NameGuidPair `json:"Genres,omitempty"`
	Tags *[]string `json:"Tags,omitempty"`
}
