/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// ImageByNameInfo struct for ImageByNameInfo
type ImageByNameInfo struct {
	// Gets or sets the name.
	Name *string `json:"Name,omitempty"`
	// Gets or sets the theme.
	Theme *string `json:"Theme,omitempty"`
	// Gets or sets the context.
	Context *string `json:"Context,omitempty"`
	// Gets or sets the length of the file.
	FileLength int64 `json:"FileLength,omitempty"`
	// Gets or sets the format.
	Format *string `json:"Format,omitempty"`
}
