/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
import (
	"time"
)
// TimerInfoDto struct for TimerInfoDto
type TimerInfoDto struct {
	// Id of the recording.
	Id *string `json:"Id,omitempty"`
	Type *string `json:"Type,omitempty"`
	// Gets or sets the server identifier.
	ServerId *string `json:"ServerId,omitempty"`
	// Gets or sets the external identifier.
	ExternalId *string `json:"ExternalId,omitempty"`
	// ChannelId of the recording.
	ChannelId string `json:"ChannelId,omitempty"`
	// Gets or sets the external channel identifier.
	ExternalChannelId *string `json:"ExternalChannelId,omitempty"`
	// ChannelName of the recording.
	ChannelName *string `json:"ChannelName,omitempty"`
	ChannelPrimaryImageTag *string `json:"ChannelPrimaryImageTag,omitempty"`
	// Gets or sets the program identifier.
	ProgramId *string `json:"ProgramId,omitempty"`
	// Gets or sets the external program identifier.
	ExternalProgramId *string `json:"ExternalProgramId,omitempty"`
	// Name of the recording.
	Name *string `json:"Name,omitempty"`
	// Description of the recording.
	Overview *string `json:"Overview,omitempty"`
	// The start date of the recording, in UTC.
	StartDate time.Time `json:"StartDate,omitempty"`
	// The end date of the recording, in UTC.
	EndDate time.Time `json:"EndDate,omitempty"`
	// Gets or sets the name of the service.
	ServiceName *string `json:"ServiceName,omitempty"`
	// Gets or sets the priority.
	Priority int32 `json:"Priority,omitempty"`
	// Gets or sets the pre padding seconds.
	PrePaddingSeconds int32 `json:"PrePaddingSeconds,omitempty"`
	// Gets or sets the post padding seconds.
	PostPaddingSeconds int32 `json:"PostPaddingSeconds,omitempty"`
	// Gets or sets a value indicating whether this instance is pre padding required.
	IsPrePaddingRequired bool `json:"IsPrePaddingRequired,omitempty"`
	// If the item does not have any backdrops, this will hold the Id of the Parent that has one.
	ParentBackdropItemId *string `json:"ParentBackdropItemId,omitempty"`
	// Gets or sets the parent backdrop image tags.
	ParentBackdropImageTags *[]string `json:"ParentBackdropImageTags,omitempty"`
	// Gets or sets a value indicating whether this instance is post padding required.
	IsPostPaddingRequired bool `json:"IsPostPaddingRequired,omitempty"`
	KeepUntil KeepUntil `json:"KeepUntil,omitempty"`
	Status RecordingStatus `json:"Status,omitempty"`
	// Gets or sets the series timer identifier.
	SeriesTimerId *string `json:"SeriesTimerId,omitempty"`
	// Gets or sets the external series timer identifier.
	ExternalSeriesTimerId *string `json:"ExternalSeriesTimerId,omitempty"`
	// Gets or sets the run time ticks.
	RunTimeTicks *int64 `json:"RunTimeTicks,omitempty"`
	ProgramInfo BaseItemDto `json:"ProgramInfo,omitempty"`
}
