/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// ProgramAudio the model 'ProgramAudio'
type ProgramAudio string

// List of ProgramAudio
const (
	PROGRAMAUDIO_MONO ProgramAudio = "Mono"
	PROGRAMAUDIO_STEREO ProgramAudio = "Stereo"
	PROGRAMAUDIO_DOLBY ProgramAudio = "Dolby"
	PROGRAMAUDIO_DOLBY_DIGITAL ProgramAudio = "DolbyDigital"
	PROGRAMAUDIO_THX ProgramAudio = "Thx"
	PROGRAMAUDIO_ATMOS ProgramAudio = "Atmos"
)
