/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// MediaSourceType the model 'MediaSourceType'
type MediaSourceType string

// List of MediaSourceType
const (
	MEDIASOURCETYPE_DEFAULT MediaSourceType = "Default"
	MEDIASOURCETYPE_GROUPING MediaSourceType = "Grouping"
	MEDIASOURCETYPE_PLACEHOLDER MediaSourceType = "Placeholder"
)
