/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// MediaPathInfo struct for MediaPathInfo
type MediaPathInfo struct {
	Path *string `json:"Path,omitempty"`
	NetworkPath *string `json:"NetworkPath,omitempty"`
}
