/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// PlaystateCommand Enum PlaystateCommand.
type PlaystateCommand string

// List of PlaystateCommand
const (
	PLAYSTATECOMMAND_STOP PlaystateCommand = "Stop"
	PLAYSTATECOMMAND_PAUSE PlaystateCommand = "Pause"
	PLAYSTATECOMMAND_UNPAUSE PlaystateCommand = "Unpause"
	PLAYSTATECOMMAND_NEXT_TRACK PlaystateCommand = "NextTrack"
	PLAYSTATECOMMAND_PREVIOUS_TRACK PlaystateCommand = "PreviousTrack"
	PLAYSTATECOMMAND_SEEK PlaystateCommand = "Seek"
	PLAYSTATECOMMAND_REWIND PlaystateCommand = "Rewind"
	PLAYSTATECOMMAND_FAST_FORWARD PlaystateCommand = "FastForward"
	PLAYSTATECOMMAND_PLAY_PAUSE PlaystateCommand = "PlayPause"
)
