/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// HeaderMatchType the model 'HeaderMatchType'
type HeaderMatchType string

// List of HeaderMatchType
const (
	HEADERMATCHTYPE_EQUALS HeaderMatchType = "Equals"
	HEADERMATCHTYPE_REGEX HeaderMatchType = "Regex"
	HEADERMATCHTYPE_SUBSTRING HeaderMatchType = "Substring"
)
