/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// GroupUpdateType Enum GroupUpdateType.
type GroupUpdateType string

// List of GroupUpdateType
const (
	GROUPUPDATETYPE_USER_JOINED GroupUpdateType = "UserJoined"
	GROUPUPDATETYPE_USER_LEFT GroupUpdateType = "UserLeft"
	GROUPUPDATETYPE_GROUP_JOINED GroupUpdateType = "GroupJoined"
	GROUPUPDATETYPE_GROUP_LEFT GroupUpdateType = "GroupLeft"
	GROUPUPDATETYPE_GROUP_WAIT GroupUpdateType = "GroupWait"
	GROUPUPDATETYPE_PREPARE_SESSION GroupUpdateType = "PrepareSession"
	GROUPUPDATETYPE_NOT_IN_GROUP GroupUpdateType = "NotInGroup"
	GROUPUPDATETYPE_GROUP_DOES_NOT_EXIST GroupUpdateType = "GroupDoesNotExist"
	GROUPUPDATETYPE_CREATE_GROUP_DENIED GroupUpdateType = "CreateGroupDenied"
	GROUPUPDATETYPE_JOIN_GROUP_DENIED GroupUpdateType = "JoinGroupDenied"
	GROUPUPDATETYPE_LIBRARY_ACCESS_DENIED GroupUpdateType = "LibraryAccessDenied"
)
