/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// XmlAttribute struct for XmlAttribute
type XmlAttribute struct {
	Name *string `json:"Name,omitempty"`
	Value *string `json:"Value,omitempty"`
}
